GET https://notekeeper-api-megn.onrender.com/notes

POST  https://notekeeper-api-megn.onrender.com/notes

Content-Type: application/json

{
	"name": "Yasir el Bouazzati",
	"description": "I'm the best web designer",
	"important": true,
	"status": "pending",
	"dueDate": "1/1/2024"
}


PUT  https://notekeeper-api-megn.onrender.com/notes/sBHLr-1714336266170

Content-Type: application/json


{
	"status": "in progress"
}


DELETE  https://notekeeper-api-megn.onrender.com/notes/512Zv-1714414789107
